parameters:
#    irvyne_core.frontend_navbar.class: Irvyne\CoreBundle\Example

services:
    irvyne_core.backend_navbar:
        class: '%mopa_bootstrap.navbar.generic%'
        scope: request
        arguments:
            - { leftmenu: @irvyne_core.backend_navbar.main_menu }
            - {}
            - { title: 'Irvyne', titleRoute: 'irvyne_core_homepage', fixedTop: true, isFluid: true }
        tags:
            - { name: mopa_bootstrap.navbar, alias: backendNavbar }

    irvyne_core.backend_navbar.menu_builder:
        class: Irvyne\CoreBundle\Menu\BackendNavbarMenuBuilder
        scope: request
        arguments: [ '@knp_menu.factory', '@security.context' ]

    irvyne_core.backend_navbar.main_menu:
        class: Knp\Menu\MenuItem
        factory_service: irvyne_core.backend_navbar.menu_builder
        factory_method: createMainMenu
        arguments: [ '@request' ]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main }
