imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Deprecated in 2.0; will be removed in 2.3 (used trusted_proxies instead)
    trusted_proxies: ~
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    #bundles:        [ ]
    #java: /usr/bin/java #Unix
    #java: "c:\\Program Files\\Java\\jre6\\bin\\java.exe" #Java6 Windows x86 Java
    #java: "c:\\Program Files (x86)\\Java\\jre6\\bin\\java.exe" #Java6 Windows x64 Java
    java: "c:\\Program Files (x86)\\Java\\jre7\\bin\\java.exe" #Java7 Windows8 x64 Java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.8pre.jar
            #apply_to: "\.css"
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.8pre.jar
            #apply_to: "\.js"
        lessphp:
            #node: /usr/bin/node #Unix
            #node_paths: [/opt/lessc/lib, /usr/lib/node_modules] #Unix
            #node: "c:\\Program Files\\nodejs\\node.exe" #Windows x64
            #node_paths: ["c:\\Program Files\\nodejs\\node_modules\\npm\\lib", "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modules"] #Windows x64
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            apply_to: "\.less$"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        # DoctrineExtensions
        mappings:
            gedmo_translatable:
                type: annotation
                prefix: Gedmo\Translatable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity/MappedSuperclass"
                alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
                is_bundle: false
            gedmo_translator:
                type: annotation
                prefix: Gedmo\Translator\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                alias: GedmoTranslator # this one is optional and will default to the name set for the mapping
                is_bundle: false
            gedmo_loggable:
                type: annotation
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity/MappedSuperclass"
                alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                is_bundle: false
            gedmo_tree:
                type: annotation
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                alias: GedmoTree # this one is optional and will default to the name set for the mapping
                is_bundle: false

# Swiftmailer Configuration
swiftmailer:
    transport:  %mailer_transport%
    port:       %mailer_port%
    host:       %mailer_host%
    encryption: %mailer_encryption%
    auth_mode:  %mailer_auth_mode%
    username:   %mailer_user%
    password:   %mailer_password%
    spool:      { type: memory }

# JSMI18n Configuration
jms_i18n_routing:
    default_locale: %locale%
    locales:        [fr, en]
    strategy:       custom
    hosts:
        fr: irvyne_dev.fr
        en: irvyne_dev.com
    redirect_to_host: true

# StofDoctrineExtensionsBundle
stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            blameable:      true
            loggable:       true
            sluggable:      true
            sortable:       true
            timestampable:  true
            translatable:   true
            tree:           true

# FOSUser Configuration
fos_user:
    db_driver:      orm
    firewall_name:  fos_user
    user_class:     Irvyne\UserBundle\Entity\User

# MopaBootstrap Configuration
mopa_bootstrap:
    navbar: ~
    initializr:
        meta:
            title:        "YYY"
            description:  "Blog with tutorials for global web and development"
            keywords:     "blog, tutorials, development, web, symfony2, php"
            author_name:  "Thibaud BARDIN"
            author_url:   "http://thibaud-bardin.com"
            nofollow:     true
            noindex:      true
        dns_prefetch:
              - '//ajax.googleapis.com'
        google:
            wt: 'xxx'
            analytics: 'UA-xxxxxxx-xx'
        diagnostic_mode: true

# Trsteel CKeditor Configuration
trsteel_ckeditor:
    toolbar: ['document', 'clipboard', 'editing', '/', 'basicstyles', 'paragraph', 'links', '/', 'insert', 'styles', 'tools']
    toolbar_groups:
        document: ['Source', 'Code']
    external_plugins:
            syntaxhighlight:
                path: bundles/irvynecore/js/ckeditor/plugins/syntaxhighlight-1.0

# Services
services:
    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension
