parameters:
    database_driver:    ~ #pdo_mysql
    database_host:      ~ #127.0.0.1
    database_port:      ~ #null
    database_name:      ~ #irvyne
    database_user:      ~ #root
    database_password:  ~ #null
    database_path:      ~ #null

    mailer_transport:   ~
    mailer_port:        ~ #587
    mailer_host:        ~ #in.mailjet.com
    mailer_encryption:  ~ #tls
    mailer_auth_mode:   ~ #login
    mailer_user:        ~ #null
    mailer_password:    ~ #null

    locale:             ~ #fr
    secret:             ThisTokenIsNotSoSecretChangeIt
