irvyne_ck_editor_plugin:
    resource: "@IrvyneCKEditorPluginBundle/Resources/config/routing.yml"
    prefix:   /

irvyne_blog:
    resource: "@IrvyneBlogBundle/Resources/config/routing.yml"
    prefix:   /

irvyne_user:
    resource: "@IrvyneUserBundle/Resources/config/routing.yml"
    prefix:   /

irvyne_core:
    resource: "@IrvyneCoreBundle/Resources/config/routing.yml"
    prefix:   /

genemu_image:
    resource: "@GenemuFormBundle/Resources/config/routing/image.xml"
