IrvyneBlogBundle_article:
    resource: "@IrvyneBlogBundle/Resources/config/routing/article.yml"
    prefix: /

IrvyneBlogBundle_category:
    resource: "@IrvyneBlogBundle/Resources/config/routing/category.yml"
    prefix: /