article:
    pattern:  /articles
    defaults: { _controller: "IrvyneBlogBundle:Article:index" }

article_new:
    pattern:  /article/new
    defaults: { _controller: "IrvyneBlogBundle:Article:new" }

article_create:
    pattern:  /article/create
    defaults: { _controller: "IrvyneBlogBundle:Article:create" }
    requirements: { _method: post }

article_show:
    pattern:  /article/{slug}
    defaults: { _controller: "IrvyneBlogBundle:Article:show" }

article_edit:
    pattern:  /article/{id}/edit
    defaults: { _controller: "IrvyneBlogBundle:Article:edit" }

article_update:
    pattern:  /article/{id}/update
    defaults: { _controller: "IrvyneBlogBundle:Article:update" }
    requirements: { _method: post }

article_delete:
    pattern:  /article/{id}/delete
    defaults: { _controller: "IrvyneBlogBundle:Article:delete" }
    requirements: { _method: post }
