article:
    pattern:  /admin/articles
    defaults: { _controller: "IrvyneBlogBundle:Article:index" }

article_new:
    pattern:  /admin/article/new
    defaults: { _controller: "IrvyneBlogBundle:Article:new" }

article_create:
    pattern:  /admin/article/create
    defaults: { _controller: "IrvyneBlogBundle:Article:create" }
    requirements: { _method: post }

article_show:
    pattern:  /admin/article/{slug}
    defaults: { _controller: "IrvyneBlogBundle:Article:show" }

article_edit:
    pattern:  /admin/article/{id}/edit
    defaults: { _controller: "IrvyneBlogBundle:Article:edit" }

article_update:
    pattern:  /admin/article/{id}/update
    defaults: { _controller: "IrvyneBlogBundle:Article:update" }
    requirements: { _method: post }

article_enabled:
    pattern: /admin/article/{id}/enabled/{boolean}
    defaults: { _controller: "IrvyneBlogBundle:Article:enabled" }
    requirements: { _method: post, boolean: true|false }

article_delete:
    pattern:  /admin/article/{id}/delete
    defaults: { _controller: "IrvyneBlogBundle:Article:delete" }
    requirements: { _method: post }
