category:
    pattern:  /admin/categories
    defaults: { _controller: "IrvyneBlogBundle:Category:index" }

category_new:
    pattern:  /admin/category/new
    defaults: { _controller: "IrvyneBlogBundle:Category:new" }

category_create:
    pattern:  /admin/category/create
    defaults: { _controller: "IrvyneBlogBundle:Category:create" }
    requirements: { _method: post }

category_show:
    pattern:  /admin/category/{slug}
    defaults: { _controller: "IrvyneBlogBundle:Category:show" }

category_edit:
    pattern:  /admin/category/{id}/edit
    defaults: { _controller: "IrvyneBlogBundle:Category:edit" }

category_update:
    pattern:  /admin/category/{id}/update
    defaults: { _controller: "IrvyneBlogBundle:Category:update" }
    requirements: { _method: post }

category_delete:
    pattern:  /admin/category/{id}/delete
    defaults: { _controller: "IrvyneBlogBundle:Category:delete" }
    requirements: { _method: post }
